services:
  app:
    build:
      context: .
      target: app
      args:
        UID: 1000
        GID: 1000
    volumes:
    - ./config.json:/server-status/config.json
  builder:
    build:
      context: .
      target: build
    profiles: ["build"]
    working_dir: /build
    volumes:
    - .:/build
    - go-mod-cache:/go/pkg/mod
    - go-build-cache:/root/.cache/go-build
    command: sh -c "git config --global --add safe.directory /build && go get && make linux && chown -R 1000:1000 /build/dist"
  scanner:
    build:
      context: .
      target: scan
    profiles: ["scan"]
    working_dir: /build
    volumes:
    - .:/build
    - go-mod-cache:/go/pkg/mod
    command: sh -c "git config --global --add safe.directory /build && go get && govulncheck -show verbose ./..."

volumes:
  go-mod-cache:
  go-build-cache:
